"""rename to artist name and venue name in Booking

Revision ID: 0fa17253848a
Revises: a0c670ff6d5f
Create Date: 2023-08-21 14:18:08.847475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa17253848a'
down_revision = 'a0c670ff6d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('artist_name', sa.String(), nullable=True))
    op.add_column('booking', sa.Column('venue_name', sa.String(), nullable=True))
    op.drop_column('booking', 'venue')
    op.drop_column('booking', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.add_column('booking', sa.Column('venue', sa.VARCHAR(), nullable=True))
    op.drop_column('booking', 'venue_name')
    op.drop_column('booking', 'artist_name')
    # ### end Alembic commands ###
