"""drop tables to add price to Booking

Revision ID: 3084b4f9a9bd
Revises: 581b661a12f0
Create Date: 2023-08-23 03:41:38.534978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3084b4f9a9bd"
down_revision = "581b661a12f0"
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table("booking")
    op.drop_table("venue")
    op.drop_table("artist")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
