"""drop tables to remove backref in booking

Revision ID: 553cd82783d0
Revises: a7a01960fa58
Create Date: 2023-08-16 07:16:31.816636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "553cd82783d0"
down_revision = "a7a01960fa58"
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table("booking")
    op.drop_table("venue")
    op.drop_table("artist")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
