"""modify booking table remove artist name venue name

Revision ID: 5937ed9599fe
Revises: 3da455692bfb
Create Date: 2023-08-22 08:01:12.331050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5937ed9599fe"
down_revision = "3da455692bfb"
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table("booking")
    op.drop_table("venue")
    op.drop_table("artist")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
