"""drop tables to change booking table

Revision ID: 6a89f7136e6e
Revises: 9c01fedf95a0
Create Date: 2023-08-16 05:38:01.112651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6a89f7136e6e"
down_revision = "9c01fedf95a0"
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table("booking")
    op.drop_table("venue")
    op.drop_table("artist")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
