"""drop tables for schema version 10

Revision ID: 72bab9c35505
Revises: 7e746ae6cf0d
Create Date: 2023-08-22 08:39:55.472902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "72bab9c35505"
down_revision = "7e746ae6cf0d"
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table("booking")
    op.drop_table("venue")
    op.drop_table("artist")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
