"""drop table to remove address from Venue class

Revision ID: 773a3c722652
Revises: b4376da240ad
Create Date: 2023-08-16 16:55:26.837935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "773a3c722652"
down_revision = "b4376da240ad"
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table("booking")
    op.drop_table("venue")
    op.drop_table("artist")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
