"""drop tables after removing backref from artist and venue

Revision ID: 7e746ae6cf0d
Revises: 0524cd4a23ae
Create Date: 2023-08-22 08:37:15.454949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7e746ae6cf0d"
down_revision = "0524cd4a23ae"
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table("booking")
    op.drop_table("venue")
    op.drop_table("artist")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
