"""drop tables to regnerate schema

Revision ID: a4c32ce50f87
Revises: 0fa17253848a
Create Date: 2023-08-21 14:37:38.306486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a4c32ce50f87"
down_revision = "0fa17253848a"
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table("booking")
    op.drop_table("venue")
    op.drop_table("artist")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
