"""modifies Booking table fixes relationship

Revision ID: e025e1c88e9b
Revises: 8aa609ed308b
Create Date: 2023-08-22 08:10:07.032246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e025e1c88e9b"
down_revision = "8aa609ed308b"
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table("booking")
    op.drop_table("venue")
    op.drop_table("artist")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
